<div class="block comment-list" id="customer-comments">
    <div class="block-title"><strong>Comments</strong></div>

    <?php
    $commentsCollection = $block->getCollection();
    $currentProduct = $block->getCurrentProduct();
    $currentProductId = $currentProduct->getId();
    $format = $block->getDateFormat() ?: \IntlDateFormatter::FULL;
    ?>


    <?php foreach ($commentsCollection as $comments) : ?>

        <?php $productId = $comments->getProductId();
        $status = $comments->getStatusId();
        if ($productId == $currentProductId && $status == "1") : ?>
            <div class="col-md-2 col-sm-2 hidden-xs">

            </div>
            <div class="col-md-10 col-sm-10">
                <div class="panel panel-default arrow left">
                    <div class="panel-body">
                        <header class="text-left">
                            <div class="comment-user"><i class="fa fa-user"></i> <?php echo $comments->getName() ?>
                            </div>
                            <time class="comment-date"><i
                                        class="fa fa-clock-o"></i> <?= $block->escapeHtmlAttr($block->formatDate($comments->getCreatedAt(), $format)) ?>
                            </time>

                        </header>
                        <div class="comment-post">
                            <p>
                                <?php echo $comments->getComment() ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>


        <?php endif; ?>

    <?php endforeach; ?>
    <div class="toolbar bottom">
        <?php echo $block->getPagerHtml(); ?>
    </div>
</div>











